// file generated by .bin/download-plugins-readme.js
export default [
  {
    "text": "Helpers",
    "link": "/tools/helpers"
  },
  {
    "text": "Plugin Platform Init",
    "link": "/plugins/platform-init"
  },
  {
    "text": "Plugin Sync",
    "link": "/plugins/sync"
  },
  {
    "text": "Plugin Filesystem",
    "link": "/plugins/filesystem"
  },
  {
    "text": "Plugin Scripting",
    "link": "/plugins/scripting"
  },
  {
    "text": "Plugin Checkin",
    "link": "/plugins/checkin"
  },
  {
    "text": "Plugin Position",
    "link": "/plugins/position"
  },
  {
    "text": "Plugin Logger",
    "link": "/plugins/logger"
  }
];
