// file generated by .bin/download-plugins-readme.js
export default {
  text: 'Plugins',
  items: [
  {
    "text": "Filesystem",
    "link": "/plugins/filesystem"
  },
  {
    "text": "Platform Init",
    "link": "/plugins/platform-init"
  },
  {
    "text": "Position",
    "link": "/plugins/position"
  },
  {
    "text": "Scripting",
    "link": "/plugins/scripting"
  },
  {
    "text": "Sync",
    "link": "/plugins/sync"
  }
],
};
